apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: backend
  namespace: gitops

spec:
  project: default

  source:
    repoURL: https://github.com/codefunss/gitops-demo
    targetRevision: main
    path: backend

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true